spring:
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 1
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms


#    host: 192.168.1.37
    # cluster搭建参考：https://baijiahao.baidu.com/s?id=1634324060462017531&wfr=spider&for=pc
    # redis-cli --cluster create ip1:port1 ip2:port2 ip3:port3
    # cluster集群解除：进入src目录，删除nodes-XX.conf和appendonly.aof，不然会报错：
    #[ERR] Node XXX is not empty. Either the node already knows other nodes (check with CLUSTER NODES) or contains some key in database 0
#    cluster:
#      nodes: 192.168.1.128:6380, 192.168.1.128:6381, 192.168.1.128:6382
